frontend/src/components/Board/BoardTemplate.tsx
frontend/src/components/OptionButton.tsx
frontend/src/components/modals/BanModal/BanModal.tsx
frontend/src/components/modals/ModalContainer.tsx
frontend/src/components/modals/ProfileCardModal.tsx
frontend/src/components/modals/ProfileCardModal/ProfileCardModal.tsx
frontend/src/components/modals/ReportModal/ReportModal.tsx
frontend/src/index.css
frontend/src/main.tsx
frontend/src/pages/Layout.tsx
frontend/src/recoil/atom.ts
frontend/src/types/enum/modal.enum.ts
frontend/src/types/interface/modal.interface.ts
frontend/src/types/interface/user.interface.ts

Frontend detached

---

frontend/src/components/Board/BoardPhotoBox.tsx
frontend/src/components/Board/BoardTemplate.tsx
frontend/src/components/LeftMenuSection.tsx
frontend/src/components/RightSection/CommentSection/CommentSection.tsx
frontend/src/components/RightSection/RightSection.tsx
frontend/src/components/skeletonView/SkeletonBoardTemplate.tsx
frontend/src/index.css
frontend/src/pages/Layout.tsx
frontend/src/pages/Mainpage.tsx

> 기존 Layout, MainPage, BoardTemplate의 styled-components를 모바일, 태블릿 환경에 맞게 css를 수정했습니다. 그에 따라 바뀐 RightSection의 css는 아직 처리하지 못한 상태입니다.
https://github.com/42pet/42pet/issues/#8

[FE] FEAT: Layout, LeftMenu, MainPage, BoardTemplate 반응형 수정

---

frontend/src/components/AnimalButtonContainer.tsx
frontend/src/components/OptionButton.tsx
frontend/src/components/modals/ModalLayout.tsx
frontend/src/components/modals/ReportModal/ReportCategoryOption.tsx
frontend/src/index.css
frontend/src/pages/SignUpPage/ProfileCard.tsx
frontend/src/pages/SignUpPage/SignUpPage.tsx
frontend/src/recoil/atom.ts
frontend/src/types/dto/board.dto.ts
frontend/src/types/interface/board.interface.ts
frontend/src/types/interface/modal.interface.ts
frontend/src/types/interface/right.section.interface.ts
frontend/src/types/interface/user.interface.ts

> 제목과 같게 기존의 인터페이스, DTO, atom에 설명 주석을 추가해 다른 팀원들이 이해하기 쉽게 수정하였습니다.
https://github.com/42pet/42pet/issues/11

[FE] FEAT: 인터페이스, DTO, atom에 대해 설명 주석 추가

---

backend/src/main/java/proj/pet/board/domain/Board.java
backend/src/main/java/proj/pet/category/controller/CategoryController.java
backend/src/main/java/proj/pet/category/dto/CategoryUpdateRequestDto.java
backend/src/main/java/proj/pet/category/service/CategoryFacadeService.java
backend/src/main/java/proj/pet/category/service/CategoryFacadeServiceImpl.java
backend/src/main/java/proj/pet/category/service/CategoryService.java
backend/src/main/java/proj/pet/category/service/CategoryServiceImpl.java
backend/src/main/java/proj/pet/member/domain/Member.java
backend/src/test/java/proj/pet/category/controller/CategoryControllerTest.java

아가 형석의 요청으로 단순 API추가여서 dev로 바로 머지.

[BE] FEAT: updateCategories API 추가

---

frontend/.gitignore
frontend/src/components/Board/BoardPhotoBox.tsx
frontend/src/components/Board/BoardTemplate.tsx

[FE] REFACTOR: BoardTemplate 일부 수정

---

backend/src/main/java/proj/pet/follow/controller/FollowController.java
frontend/src/api/axios/axios.custom.ts
frontend/src/components/FollowTypeButton.tsx
frontend/src/components/RightSection/FollowerSection/FollowerSection.tsx
frontend/src/components/RightSection/FollowingSection/FollowingSection.tsx
frontend/src/components/RightSection/RightSection.tsx
frontend/src/hooks/useFetch.tsx
frontend/src/pages/ProfilePage/Component/ProfileInfoComponent.tsx
frontend/src/pages/ProfilePage/MyProfilePage.tsx
frontend/src/pages/ProfilePage/ProfilePage.tsx
frontend/src/types/dto/member.dto.ts

[FE] FEAT: 프로필에서 팔로우/팔로잉 버튼 누를 시 팔로우/팔로잉 목록 보여주기 구현

---

frontend/src/components/OptionButton/ProfileOption.tsx
frontend/src/components/RightSection/BannedMemberSection/BannedMemberSection.tsx

1. 일단 명세가 다른 것 같아서 그거에 맞춰서 가져오게 함.
2. 차단직후에 바로 들어가서 불러오면 fetch가 잘 안되어서 그 부분 문제 해결

[FE] FIX: 차단목록 가져오기

---

frontend/src/api/axios/axios.custom.ts
frontend/src/components/RightSection/BannedMemberSection/BannedMemberSection.tsx
frontend/src/components/RightSection/FollowerSection/FollowerSection.tsx
frontend/src/components/modals/BanModal/BanModal.tsx

axios.get의 요청 url에 api가 안붙어있어서 추가

[FE] FIX: axios.get에서 요청 url 수정

---

frontend/src/pages/ImageCropper.tsx
frontend/src/pages/ImageUploader.tsx

[FE]업로드 창 모바일 뷰 고려 수정완료: 이벤트 관련 추가 수정 요망

---

frontend/package.json
frontend/src/api/axios/axios.custom.ts
frontend/src/components/OptionButton/ProfileOption.tsx
frontend/src/components/modals/ProfileEditModal/ProfileEditModal.tsx
frontend/src/hooks/useFetch.tsx
frontend/src/pages/Layout.tsx
frontend/src/pages/ProfilePage/MyProfilePage.tsx
frontend/src/pages/SignUpPage/Sections/IntroductionSection.tsx
frontend/src/recoil/atom.ts
frontend/src/types/dto/member.dto.ts
frontend/src/types/interface/profile.interface.ts

일단 프로필 수정기능만 구현했고, 디자인은 고려하지 않음.
코드도 조금 복잡하긴 함.
- 프로필 사진 기본 프로필로 변경하는 기능 구현
- 디자인 수정
- NicknameUpdatedAt 기준으로 30일동안은 닉네임 수정 못하게 하기
- 이미지 용량 제한

[FE] FEAT: 프로필 수정 구현 - 일부 보완 필요

---

frontend/src/api/axios/axios.custom.ts
frontend/src/components/modals/ProfileEditModal/ProfileEditModal.tsx

프로필 닉네임 30일 내에 재수정 불가 기능 구현
- 다음 수정 가능 기간 toast로 띄움

[FE] FEAT: 프로필 닉네임 30일 내에 재수정 불가 기능 구현

---

frontend/src/components/modals/ProfileEditModal/ProfileEditModal.tsx

[FE] FIX: heic 테스트

---

frontend/src/pages/ImageUploader.tsx

[FE]업로드 파일 압축 메소드 적용 : 민관이형 코드 참고

---

frontend/package-lock.json
frontend/src/components/RightSection/AnimalFilterSection/AnimalFilterSection.tsx
frontend/src/components/RightSection/BannedMemberSection/BannedMemberSection.tsx
frontend/src/components/RightSection/CommentSection/CommentSection.tsx
frontend/src/components/modals/BanModal/BanModal.tsx
frontend/src/components/modals/DeleteModal/DeleteModal.tsx
frontend/src/components/modals/MeatballModal.tsx
frontend/src/components/modals/ProfileCardModal/ProfileCardModal.tsx
frontend/src/components/modals/ProfileEditModal/ProfileEditModal.tsx
frontend/src/components/modals/ReportModal/ReportModal.tsx

[FE]언어 컴포넌트 교체중

---

backend/src/main/java/proj/pet/block/controller/BlockController.java
backend/src/main/java/proj/pet/block/dto/BlockRequestDto.java
backend/src/main/java/proj/pet/board/controller/BoardController.java
backend/src/main/java/proj/pet/board/dto/BoardCreateRequestDto.java
backend/src/main/java/proj/pet/category/controller/CategoryController.java
backend/src/main/java/proj/pet/category/dto/CategoryUpdateRequestDto.java
backend/src/main/java/proj/pet/comment/controller/CommentController.java
backend/src/main/java/proj/pet/comment/dto/CommentCreateRequestDto.java
backend/src/main/java/proj/pet/comment/service/CommentFacadeService.java
backend/src/main/java/proj/pet/comment/service/CommentFacadeServiceImpl.java
backend/src/main/java/proj/pet/follow/controller/FollowController.java
backend/src/main/java/proj/pet/follow/dto/FollowRequestDto.java
backend/src/main/java/proj/pet/member/contorller/MemberController.java
backend/src/main/java/proj/pet/member/dto/MemberCreateRequestDto.java
backend/src/main/java/proj/pet/member/dto/MemberLanguageChangeRequestDto.java
backend/src/main/java/proj/pet/member/dto/MemberProfileChangeRequestDto.java
backend/src/main/java/proj/pet/reaction/controller/ReactionController.java
backend/src/main/java/proj/pet/reaction/dto/ReactionRequestDto.java
backend/src/main/java/proj/pet/report/controller/ReportController.java
backend/src/main/java/proj/pet/report/dto/ReportRequestDto.java
backend/src/main/java/proj/pet/scrap/controller/ScrapController.java
backend/src/main/java/proj/pet/scrap/dto/ScrapCreateRequestDto.java

[BE] FEAT : Controller에서 Body를 받는 부분들에 대해서 Validation 적용

---

backend/src/main/java/proj/pet/utils/domain/ControllerLog.java

[BE] FEAT: Controller에 AOP로 Logging 구현

---

frontend/package.json
frontend/src/hooks/useNicknameValidation.tsx

hook이 컴포넌트 최상단에 있지 않아서 signup에서 넘어가지 않는 문제 해결

[FE] FIX: 언어 변경 hook 에러 수정

---

frontend/src/components/AnimalButtonContainer.tsx
frontend/src/pages/SignUpPage/SignUpPage.tsx

>아래 링크에 이슈번호를 적어주세요. 예) .../42pet/issues/119
https://github.com/42pet/42pet/issues/119

[FE] FIX: SignUp 언어 설정 반영

---

frontend/src/hooks/useNavigateCustom.tsx
frontend/src/pages/ProfilePage/ProfilePage.tsx

팔로우목록 통해서 타인 프로필 갔을 때 게시물 잘못 불러오는 문제 해결

[FE] FIX: 팔로우목록 통해서 타인 프로필 갔을 때 게시물 잘못 불러오는 문제 해결

---

frontend/package-lock.json
frontend/src/components/LeftMenuSection/LeftMenuTablet.tsx
frontend/src/pages/ImageUploader.tsx
frontend/src/pages/UploadPage.tsx

Fe/dev/fix upload/#121

---

frontend/src/pages/ImageUploader.tsx

Fe/dev/fix upload/#125

---

backend/src/main/java/proj/pet/member/service/MemberQueryServiceImpl.java
backend/src/main/java/proj/pet/member/service/MemberServiceImpl.java
backend/src/main/java/proj/pet/member/validation/NicknameValidation.java

[BE] FIX: nickname validation 추가 및 적용 확인

---

frontend/src/pages/ImageUploader.tsx

Fe/dev/bug upload/#134

---

frontend/src/pages/ImageUploader.tsx

[FE]업로드 로직 정리

---

frontend/src/types/enum/country.enum.ts

> 기존 Country enum에 싱가폴이 존재하지 않아 추가해 주었습니다.
https://github.com/42pet/42pet/issues/139

[FE] FEAT: 국가 enum 싱가폴 추가

---

backend/src/main/java/proj/pet/auth/service/AuthAspect.java
backend/src/main/java/proj/pet/board/controller/BoardController.java
backend/src/main/java/proj/pet/board/dto/BoardCreateRequestDto2.java
backend/src/main/java/proj/pet/board/service/BoardFacadeService.java
backend/src/main/java/proj/pet/board/service/BoardFacadeServiceImpl.java
backend/src/main/java/proj/pet/board/service/BoardService.java
backend/src/main/java/proj/pet/board/service/BoardServiceImpl.java
backend/src/main/java/proj/pet/notice/repository/NoticeRepository.java
frontend/src/api/axios/axios.custom.ts
frontend/src/pages/UploadPage/components/ImageUploader.tsx
frontend/src/types/dto/board.dto.ts

[FE] FEAT: presigned-url 게시물 파트 구현 

---

frontend/src/api/axios/axios.custom.ts
frontend/src/components/RightSection/CommentSection/CommentItem.tsx
frontend/src/components/RightSection/CommentSection/CommentSection.tsx
frontend/src/components/modals/ModalContainer.tsx
frontend/src/components/modals/UserNotFoundModal/UserNotFoundModal.tsx
frontend/src/pages/ImageUploader.tsx
frontend/src/recoil/atom.ts
frontend/src/types/enum/modal.enum.ts
frontend/src/types/interface/modal.interface.ts

- 댓글에서 '@' 이후 입력되는 글자를 기준으로 유저를 검색하여 보여주는 기능 추가
- 유저 검색창 밖을 클릭하거나 ESC 를 누르면 유저 검색창 닫힘
https://github.com/42PAW/42PAW/issues/146

[FE] 댓글 유저 태그 기능 추가 #146
